/* =====================================================================
   File: load_generated_data.sql
   Course: CS486 - Introduction to Database System
   Group: G10
   DBMS: Microsoft SQL Server 2022+

   Purpose:
       Bulk-load deterministic Phase 2 benchmark data generated by
       generate_data.py.

   Required execution order before this file:
       1. 05-db-definition-G10.sql
       2. 06-sample-data-G10.sql
       3. 10-schema-migration-G10.sql
       4. 12-concurrency-implementation-G10.sql

   IMPORTANT - SQLCMD MODE:
       This script uses $(DataDir). In SSMS:
         Query -> SQLCMD Mode
       Then change DataDir below to the folder that SQL Server itself can
       read. Keep a trailing slash/backslash.

       Windows example:
         :setvar DataDir "C:\CS486\14-data-generator-G10\generated\"

       Linux/Docker example after mounting the folder into the container:
         :setvar DataDir "/var/opt/mssql/data-generator/"
   ===================================================================== */

:setvar DataDir "D:\code\Database\Project_2\14-data-generator-G10\generated\"

USE CampusSpaceManagement;
GO

SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

/* =====================================================================
   1. PRECHECKS
   ===================================================================== */

IF OBJECT_ID(N'dbo.users', N'U') IS NULL
    THROW 54001, 'dbo.users is missing. Run the Phase 1 schema first.', 1;

IF OBJECT_ID(N'dbo.booking_advisory_acknowledgements', N'U') IS NULL
    THROW 54002, 'Phase 2 migration is missing. Run 10-schema-migration-G10.sql first.', 1;

IF COL_LENGTH(N'dbo.booking_requests', N'version_token') IS NULL
    THROW 54003, 'booking_requests.version_token is missing.', 1;

IF COL_LENGTH(N'dbo.approvals', N'decision_method') IS NULL
    THROW 54004, 'approvals.decision_method is missing.', 1;

IF COL_LENGTH(N'dbo.maintenance_records', N'impact_level') IS NULL
    THROW 54005, 'maintenance_records.impact_level is missing.', 1;
GO

/* =====================================================================
   2. STAGING TABLES
   All staging columns are NVARCHAR so CSV parsing is predictable.
   ===================================================================== */

DROP TABLE IF EXISTS #stg_users;
DROP TABLE IF EXISTS #stg_spaces;
DROP TABLE IF EXISTS #stg_facility_instances;
DROP TABLE IF EXISTS #stg_booking_requests;
DROP TABLE IF EXISTS #stg_approvals;
DROP TABLE IF EXISTS #stg_usage_sessions;
DROP TABLE IF EXISTS #stg_maintenance_records;
DROP TABLE IF EXISTS #stg_maintenance_assignments;
DROP TABLE IF EXISTS #stg_maintenance_escalations;
DROP TABLE IF EXISTS #stg_acknowledgements;
GO

CREATE TABLE #stg_users (
    user_id NVARCHAR(100), full_name NVARCHAR(300), email NVARCHAR(300),
    phone_number NVARCHAR(100), role NVARCHAR(100), department NVARCHAR(300),
    account_status NVARCHAR(100)
);

CREATE TABLE #stg_spaces (
    space_code NVARCHAR(100), space_name NVARCHAR(300), space_type NVARCHAR(100),
    building NVARCHAR(300), floor NVARCHAR(100), room_number NVARCHAR(100),
    capacity NVARCHAR(100), current_status NVARCHAR(100), usage_policy NVARCHAR(MAX)
);

CREATE TABLE #stg_facility_instances (
    facility_id NVARCHAR(100), facility_type_name NVARCHAR(300), space_code NVARCHAR(100),
    asset_tag NVARCHAR(300), instance_status NVARCHAR(100), condition_note NVARCHAR(MAX),
    installed_at NVARCHAR(100)
);

CREATE TABLE #stg_booking_requests (
    booking_id NVARCHAR(100), requester_id NVARCHAR(100), space_code NVARCHAR(100),
    requested_start_time NVARCHAR(100), requested_end_time NVARCHAR(100),
    purpose_of_use NVARCHAR(100), expected_participants NVARCHAR(100),
    final_booking_status NVARCHAR(100), created_at NVARCHAR(100)
);

CREATE TABLE #stg_approvals (
    booking_id NVARCHAR(100), staff_id NVARCHAR(100), decision NVARCHAR(100),
    decision_time NVARCHAR(100), decision_note NVARCHAR(MAX), rejection_reason NVARCHAR(MAX),
    decision_method NVARCHAR(100)
);

CREATE TABLE #stg_usage_sessions (
    booking_id NVARCHAR(100), actual_start_time NVARCHAR(100), checked_in_by NVARCHAR(100),
    initial_condition NVARCHAR(MAX), actual_end_time NVARCHAR(100),
    final_condition NVARCHAR(MAX), usage_notes NVARCHAR(MAX)
);

CREATE TABLE #stg_maintenance_records (
    maintenance_id NVARCHAR(100), space_code NVARCHAR(100), reporter_id NVARCHAR(100),
    facility_id NVARCHAR(100), problem_type NVARCHAR(100), problem_description NVARCHAR(MAX),
    start_time NVARCHAR(100), completion_time NVARCHAR(100), maintenance_status NVARCHAR(100),
    result_note NVARCHAR(MAX), initial_impact_level NVARCHAR(100), final_impact_level NVARCHAR(100)
);

CREATE TABLE #stg_maintenance_assignments (
    maintenance_id NVARCHAR(100), staff_id NVARCHAR(100), assigned_at NVARCHAR(100),
    unassigned_at NVARCHAR(100), assignment_role NVARCHAR(100)
);

CREATE TABLE #stg_maintenance_escalations (
    maintenance_id NVARCHAR(100), changed_by NVARCHAR(100), escalated_at NVARCHAR(100),
    new_impact_level NVARCHAR(100), change_reason NVARCHAR(MAX)
);

CREATE TABLE #stg_acknowledgements (
    booking_id NVARCHAR(100), maintenance_id NVARCHAR(100), acknowledged_at NVARCHAR(100)
);
GO

/* =====================================================================
   3. BULK READ CSV FILES
   ===================================================================== */

BULK INSERT #stg_users
FROM '$(DataDir)users.csv'
WITH (FORMAT = 'CSV', FIRSTROW = 2, FIELDQUOTE = '"', CODEPAGE = '65001', ROWTERMINATOR = '0x0a', TABLOCK);

BULK INSERT #stg_spaces
FROM '$(DataDir)spaces.csv'
WITH (FORMAT = 'CSV', FIRSTROW = 2, FIELDQUOTE = '"', CODEPAGE = '65001', ROWTERMINATOR = '0x0a', TABLOCK);

BULK INSERT #stg_facility_instances
FROM '$(DataDir)facility_instances.csv'
WITH (FORMAT = 'CSV', FIRSTROW = 2, FIELDQUOTE = '"', CODEPAGE = '65001', ROWTERMINATOR = '0x0a', TABLOCK);

BULK INSERT #stg_booking_requests
FROM '$(DataDir)booking_requests.csv'
WITH (FORMAT = 'CSV', FIRSTROW = 2, FIELDQUOTE = '"', CODEPAGE = '65001', ROWTERMINATOR = '0x0a', TABLOCK);

BULK INSERT #stg_approvals
FROM '$(DataDir)approvals.csv'
WITH (FORMAT = 'CSV', FIRSTROW = 2, FIELDQUOTE = '"', CODEPAGE = '65001', ROWTERMINATOR = '0x0a', TABLOCK);

BULK INSERT #stg_usage_sessions
FROM '$(DataDir)usage_sessions.csv'
WITH (FORMAT = 'CSV', FIRSTROW = 2, FIELDQUOTE = '"', CODEPAGE = '65001', ROWTERMINATOR = '0x0a', TABLOCK);

BULK INSERT #stg_maintenance_records
FROM '$(DataDir)maintenance_records.csv'
WITH (FORMAT = 'CSV', FIRSTROW = 2, FIELDQUOTE = '"', CODEPAGE = '65001', ROWTERMINATOR = '0x0a', TABLOCK);

BULK INSERT #stg_maintenance_assignments
FROM '$(DataDir)maintenance_assignments.csv'
WITH (FORMAT = 'CSV', FIRSTROW = 2, FIELDQUOTE = '"', CODEPAGE = '65001', ROWTERMINATOR = '0x0a', TABLOCK);

BULK INSERT #stg_maintenance_escalations
FROM '$(DataDir)maintenance_escalations.csv'
WITH (FORMAT = 'CSV', FIRSTROW = 2, FIELDQUOTE = '"', CODEPAGE = '65001', ROWTERMINATOR = '0x0a', TABLOCK);

BULK INSERT #stg_acknowledgements
FROM '$(DataDir)booking_advisory_acknowledgements.csv'
WITH (FORMAT = 'CSV', FIRSTROW = 2, FIELDQUOTE = '"', CODEPAGE = '65001', ROWTERMINATOR = '0x0a', TABLOCK);
GO

/* CSV count sanity check before changing base tables. */
IF (SELECT COUNT_BIG(*) FROM #stg_booking_requests) < 100000
    THROW 54010, 'Generated CSV contains fewer than 100,000 booking rows.', 1;

IF EXISTS (
    SELECT 1
    FROM #stg_facility_instances AS s
    LEFT JOIN dbo.facility_types AS ft
      ON ft.facility_type_name = s.facility_type_name
    WHERE ft.facility_type_id IS NULL
)
    THROW 54011, 'A generated facility type does not exist in dbo.facility_types.', 1;

/* Automatic approvals must match the Phase 2 policy configured in file 10:
   only meeting rooms are instant-approval enabled. */
IF EXISTS (
    SELECT 1
    FROM #stg_approvals AS a
    INNER JOIN #stg_booking_requests AS br
        ON CONVERT(INT, br.booking_id) = CONVERT(INT, a.booking_id)
    INNER JOIN #stg_spaces AS s
        ON s.space_code = br.space_code
    WHERE a.decision_method = N'automatic'
      AND (
            a.decision <> N'approved'
         OR NULLIF(a.staff_id, N'') IS NOT NULL
         OR s.space_type <> N'meeting room'
      )
)
    THROW 54012, 'Invalid automatic approval row in generated CSV data.', 1;

/* Equipment-specific maintenance must reference the matching normalized
   facility instance. Room-level maintenance may keep facility_id NULL. */
IF EXISTS (
    SELECT 1
    FROM #stg_maintenance_records AS mr
    LEFT JOIN #stg_facility_instances AS fi
        ON TRY_CONVERT(INT, NULLIF(mr.facility_id, N'')) = TRY_CONVERT(INT, fi.facility_id)
    WHERE (mr.problem_type = N'broken projector'
           AND (fi.facility_id IS NULL OR fi.facility_type_name <> N'Projector'))
       OR (mr.problem_type = N'air-conditioning failure'
           AND (fi.facility_id IS NULL OR fi.facility_type_name <> N'Air conditioner'))
)
    THROW 54013, 'Equipment maintenance does not reference a matching facility instance.', 1;
GO

/* =====================================================================
   4. RELOAD GENERATED DATA

   Generated users/spaces use the reserved DG prefix. Cleanup is therefore
   based on generated ownership, not on identity-number thresholds. This is
   important because SQL Server can allocate ordinary rows identity values
   above 1,000,000 after a previous benchmark load.
   ===================================================================== */

BEGIN TRY
    BEGIN TRANSACTION;

    /* Capture the currently loaded generated parent IDs before deleting any
       rows. A booking is generated if it belongs to a DG requester or DG
       space. Maintenance is generated if it belongs to a DG space. */
    DROP TABLE IF EXISTS #old_generated_booking_ids;
    DROP TABLE IF EXISTS #old_generated_maintenance_ids;

    CREATE TABLE #old_generated_booking_ids (
        booking_id INT NOT NULL PRIMARY KEY
    );

    CREATE TABLE #old_generated_maintenance_ids (
        maintenance_id INT NOT NULL PRIMARY KEY
    );

    INSERT INTO #old_generated_booking_ids (booking_id)
    SELECT br.booking_id
    FROM dbo.booking_requests AS br
    WHERE br.space_code LIKE 'DG%'
       OR br.requester_id LIKE 'DG%';

    INSERT INTO #old_generated_maintenance_ids (maintenance_id)
    SELECT mr.maintenance_id
    FROM dbo.maintenance_records AS mr
    WHERE mr.space_code LIKE 'DG%';

    /* Child-to-parent cleanup makes the script rerunnable without deleting
       unrelated rows merely because their identity value is large. */
    DELETE baa
    FROM dbo.booking_advisory_acknowledgements AS baa
    WHERE EXISTS (
              SELECT 1
              FROM #old_generated_booking_ids AS g
              WHERE g.booking_id = baa.booking_id
          )
       OR EXISTS (
              SELECT 1
              FROM #old_generated_maintenance_ids AS g
              WHERE g.maintenance_id = baa.maintenance_id
          );

    DELETE us
    FROM dbo.usage_sessions AS us
    INNER JOIN #old_generated_booking_ids AS g
        ON g.booking_id = us.booking_id;

    DELETE a
    FROM dbo.approvals AS a
    INNER JOIN #old_generated_booking_ids AS g
        ON g.booking_id = a.booking_id;

    DELETE h
    FROM dbo.maintenance_impact_history AS h
    INNER JOIN #old_generated_maintenance_ids AS g
        ON g.maintenance_id = h.maintenance_id;

    DELETE ma
    FROM dbo.maintenance_assignments AS ma
    INNER JOIN #old_generated_maintenance_ids AS g
        ON g.maintenance_id = ma.maintenance_id;

    DELETE mr
    FROM dbo.maintenance_records AS mr
    INNER JOIN #old_generated_maintenance_ids AS g
        ON g.maintenance_id = mr.maintenance_id;

    DELETE br
    FROM dbo.booking_requests AS br
    INNER JOIN #old_generated_booking_ids AS g
        ON g.booking_id = br.booking_id;

    DELETE FROM dbo.facility_instances
    WHERE space_code LIKE 'DG%';

    DELETE FROM dbo.spaces
    WHERE space_code LIKE 'DG%';

    DELETE FROM dbo.users
    WHERE user_id LIKE 'DG%';

    /* ---------------------------------------------------------------
       4.1 Generated parent rows
       --------------------------------------------------------------- */

    INSERT INTO dbo.users (
        user_id, full_name, email, phone_number, role, department, account_status
    )
    SELECT
        CONVERT(VARCHAR(20), user_id),
        CONVERT(NVARCHAR(100), full_name),
        CONVERT(VARCHAR(150), email),
        NULLIF(CONVERT(VARCHAR(30), phone_number), ''),
        CONVERT(NVARCHAR(35), role),
        CONVERT(NVARCHAR(100), department),
        CONVERT(VARCHAR(20), account_status)
    FROM #stg_users;

    INSERT INTO dbo.spaces (
        space_code, space_name, space_type, building, floor, room_number,
        capacity, current_status, usage_policy
    )
    SELECT
        CONVERT(VARCHAR(20), space_code),
        CONVERT(NVARCHAR(100), space_name),
        CONVERT(NVARCHAR(40), space_type),
        CONVERT(NVARCHAR(100), building),
        CONVERT(VARCHAR(20), floor),
        CONVERT(VARCHAR(20), room_number),
        CONVERT(INT, capacity),
        CONVERT(NVARCHAR(30), current_status),
        usage_policy
    FROM #stg_spaces;

    SET IDENTITY_INSERT dbo.facility_instances ON;

    INSERT INTO dbo.facility_instances (
        facility_id, facility_type_id, space_code, asset_tag,
        instance_status, condition_note, installed_at
    )
    SELECT
        CONVERT(INT, s.facility_id),
        ft.facility_type_id,
        CONVERT(VARCHAR(20), s.space_code),
        CONVERT(VARCHAR(100), s.asset_tag),
        CONVERT(NVARCHAR(30), s.instance_status),
        NULLIF(s.condition_note, ''),
        TRY_CONVERT(DATETIME2(0), NULLIF(s.installed_at, ''))
    FROM #stg_facility_instances AS s
    INNER JOIN dbo.facility_types AS ft
        ON ft.facility_type_name = s.facility_type_name;

    SET IDENTITY_INSERT dbo.facility_instances OFF;

    /* ---------------------------------------------------------------
       4.2 Booking workflow

       Rows that will eventually become approved/rejected/completed/
       no-show are first inserted as pending. This lets the existing
       approval and usage-session triggers perform their normal status
       synchronization instead of bypassing OLTP rules.
       --------------------------------------------------------------- */

    SET IDENTITY_INSERT dbo.booking_requests ON;

    INSERT INTO dbo.booking_requests (
        booking_id,
        requester_id,
        space_code,
        requested_start_time,
        requested_end_time,
        purpose_of_use,
        expected_participants,
        booking_status,
        created_at
    )
    SELECT
        CONVERT(INT, booking_id),
        CONVERT(VARCHAR(20), requester_id),
        CONVERT(VARCHAR(20), space_code),
        CONVERT(DATETIME2(0), requested_start_time),
        CONVERT(DATETIME2(0), requested_end_time),
        CONVERT(NVARCHAR(40), purpose_of_use),
        CONVERT(INT, expected_participants),
        CASE
            WHEN final_booking_status = N'cancelled' THEN N'cancelled'
            ELSE N'pending'
        END,
        CONVERT(DATETIME2(0), created_at)
    FROM #stg_booking_requests;

    SET IDENTITY_INSERT dbo.booking_requests OFF;

    INSERT INTO dbo.approvals (
        booking_id,
        staff_id,
        decision,
        decision_time,
        decision_note,
        rejection_reason,
        decision_method
    )
    SELECT
        CONVERT(INT, booking_id),
        NULLIF(CONVERT(VARCHAR(20), staff_id), ''),
        CONVERT(NVARCHAR(20), decision),
        CONVERT(DATETIME2(0), decision_time),
        NULLIF(decision_note, ''),
        NULLIF(rejection_reason, ''),
        CONVERT(NVARCHAR(20), decision_method)
    FROM #stg_approvals;

    INSERT INTO dbo.usage_sessions (
        booking_id,
        actual_start_time,
        checked_in_by,
        initial_condition,
        actual_end_time,
        final_condition,
        usage_notes
    )
    SELECT
        CONVERT(INT, booking_id),
        CONVERT(DATETIME2(0), actual_start_time),
        CONVERT(VARCHAR(20), checked_in_by),
        initial_condition,
        TRY_CONVERT(DATETIME2(0), NULLIF(actual_end_time, '')),
        NULLIF(final_condition, ''),
        NULLIF(usage_notes, '')
    FROM #stg_usage_sessions;

    /* No-show happens after an approved booking was not used. */
    UPDATE br
    SET booking_status = N'no-show'
    FROM dbo.booking_requests AS br
    INNER JOIN #stg_booking_requests AS s
        ON CONVERT(INT, s.booking_id) = br.booking_id
    WHERE s.final_booking_status = N'no-show';

    /* ---------------------------------------------------------------
       4.3 Maintenance, assignment, escalation, acknowledgements
       --------------------------------------------------------------- */

    SET IDENTITY_INSERT dbo.maintenance_records ON;

    INSERT INTO dbo.maintenance_records (
        maintenance_id,
        space_code,
        reporter_id,
        facility_id,
        problem_type,
        problem_description,
        start_time,
        completion_time,
        maintenance_status,
        result_note,
        impact_level
    )
    SELECT
        CONVERT(INT, maintenance_id),
        CONVERT(VARCHAR(20), space_code),
        CONVERT(VARCHAR(20), reporter_id),
        TRY_CONVERT(INT, NULLIF(facility_id, '')),
        CONVERT(NVARCHAR(50), problem_type),
        problem_description,
        CONVERT(DATETIME2(0), start_time),
        TRY_CONVERT(DATETIME2(0), NULLIF(completion_time, '')),
        CONVERT(NVARCHAR(20), maintenance_status),
        NULLIF(result_note, ''),
        CONVERT(NVARCHAR(20), initial_impact_level)
    FROM #stg_maintenance_records;

    SET IDENTITY_INSERT dbo.maintenance_records OFF;

    /* All generated escalations use one authorized actor so the set-based
       update can use one SESSION_CONTEXT value. */
    IF EXISTS (SELECT 1 FROM #stg_maintenance_escalations)
    BEGIN
        DECLARE @escalation_actor VARCHAR(20);
        SELECT TOP (1) @escalation_actor = CONVERT(VARCHAR(20), changed_by)
        FROM #stg_maintenance_escalations;

        IF EXISTS (
            SELECT 1 FROM #stg_maintenance_escalations
            WHERE CONVERT(VARCHAR(20), changed_by) <> @escalation_actor
        )
            THROW 54014, 'Generated escalation file contains multiple changed_by actors.', 1;

        EXEC sys.sp_set_session_context
            @key = N'maintenance_changed_by',
            @value = @escalation_actor;

        EXEC sys.sp_set_session_context
            @key = N'maintenance_change_reason',
            @value = N'Generated benchmark escalation from advisory to out-of-service.';

        UPDATE mr
        SET impact_level = CONVERT(NVARCHAR(20), e.new_impact_level)
        FROM dbo.maintenance_records AS mr
        INNER JOIN #stg_maintenance_escalations AS e
            ON CONVERT(INT, e.maintenance_id) = mr.maintenance_id;

        EXEC sys.sp_set_session_context
            @key = N'maintenance_changed_by', @value = NULL;
        EXEC sys.sp_set_session_context
            @key = N'maintenance_change_reason', @value = NULL;

        /* The trigger records the real load time. Backdate the generated
           history row to the deterministic historical escalation time. */
        UPDATE h
        SET changed_at = CONVERT(DATETIME2(0), e.escalated_at),
            change_reason = e.change_reason
        FROM dbo.maintenance_impact_history AS h
        INNER JOIN #stg_maintenance_escalations AS e
            ON CONVERT(INT, e.maintenance_id) = h.maintenance_id
        WHERE h.previous_impact_level = N'advisory'
          AND h.new_impact_level = N'out-of-service';
    END;

    INSERT INTO dbo.maintenance_assignments (
        maintenance_id,
        staff_id,
        assigned_at,
        unassigned_at,
        assignment_role
    )
    SELECT
        CONVERT(INT, maintenance_id),
        CONVERT(VARCHAR(20), staff_id),
        CONVERT(DATETIME2(0), assigned_at),
        TRY_CONVERT(DATETIME2(0), NULLIF(unassigned_at, '')),
        CONVERT(NVARCHAR(30), assignment_role)
    FROM #stg_maintenance_assignments;

    INSERT INTO dbo.booking_advisory_acknowledgements (
        booking_id,
        maintenance_id,
        acknowledged_at
    )
    SELECT
        CONVERT(INT, booking_id),
        CONVERT(INT, maintenance_id),
        CONVERT(DATETIME2(0), acknowledged_at)
    FROM #stg_acknowledgements;

    /* Final status must match the generator manifest/staging data. */
    IF EXISTS (
        SELECT 1
        FROM dbo.booking_requests AS br
        INNER JOIN #stg_booking_requests AS s
            ON CONVERT(INT, s.booking_id) = br.booking_id
        WHERE br.booking_status <> CONVERT(NVARCHAR(20), s.final_booking_status)
    )
        THROW 54020, 'Booking status mismatch after workflow load.', 1;

    IF EXISTS (
        SELECT 1
        FROM dbo.maintenance_records AS mr
        INNER JOIN #stg_maintenance_records AS s
            ON CONVERT(INT, s.maintenance_id) = mr.maintenance_id
        WHERE mr.impact_level <> CONVERT(NVARCHAR(20), s.final_impact_level)
    )
        THROW 54021, 'Maintenance impact level mismatch after escalation load.', 1;

    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF XACT_STATE() <> 0
        ROLLBACK TRANSACTION;

    /* Clear connection-scoped context even if the escalation update failed. */
    EXEC sys.sp_set_session_context
        @key = N'maintenance_changed_by', @value = NULL;
    EXEC sys.sp_set_session_context
        @key = N'maintenance_change_reason', @value = NULL;

    THROW;
END CATCH;
GO

/* =====================================================================
   5. REQUIRED STATISTICS REFRESH
   ===================================================================== */

UPDATE STATISTICS dbo.booking_requests WITH FULLSCAN;
UPDATE STATISTICS dbo.maintenance_records WITH FULLSCAN;
GO

/* Additional useful statistics for the reporting workload. */
UPDATE STATISTICS dbo.facility_instances WITH FULLSCAN;
UPDATE STATISTICS dbo.booking_advisory_acknowledgements WITH FULLSCAN;
GO

/* =====================================================================
   6. POST-LOAD VERIFICATION
   ===================================================================== */

PRINT N'===== GENERATED DATA SUMMARY =====';

SELECT COUNT_BIG(*) AS generated_booking_count
FROM dbo.booking_requests
WHERE space_code LIKE 'DG%';

SELECT
    booking_status,
    COUNT_BIG(*) AS booking_count,
    CAST(100.0 * COUNT_BIG(*) /
         SUM(COUNT_BIG(*)) OVER () AS DECIMAL(6,2)) AS percentage
FROM dbo.booking_requests
WHERE space_code LIKE 'DG%'
GROUP BY booking_status
ORDER BY booking_status;

SELECT
    MIN(requested_start_time) AS first_generated_booking,
    MAX(requested_end_time) AS last_generated_booking,
    COUNT(DISTINCT
        CASE
            WHEN MONTH(requested_start_time) >= 9
                THEN YEAR(requested_start_time)
            ELSE YEAR(requested_start_time) - 1
        END
    ) AS academic_year_count
FROM dbo.booking_requests
WHERE space_code LIKE 'DG%';

SELECT
    impact_level,
    maintenance_status,
    COUNT_BIG(*) AS maintenance_count
FROM dbo.maintenance_records
WHERE space_code LIKE 'DG%'
GROUP BY impact_level, maintenance_status
ORDER BY impact_level, maintenance_status;

SELECT COUNT_BIG(*) AS generated_acknowledgement_count
FROM dbo.booking_advisory_acknowledgements AS baa
INNER JOIN dbo.booking_requests AS br
    ON br.booking_id = baa.booking_id
WHERE br.space_code LIKE 'DG%';

SELECT COUNT_BIG(*) AS generated_escalation_history_count
FROM dbo.maintenance_impact_history AS h
INNER JOIN dbo.maintenance_records AS mr
    ON mr.maintenance_id = h.maintenance_id
WHERE mr.space_code LIKE 'DG%'
  AND h.previous_impact_level = N'advisory'
  AND h.new_impact_level = N'out-of-service';

SELECT
    a.decision_method,
    COUNT_BIG(*) AS approval_count
FROM dbo.approvals AS a
INNER JOIN dbo.booking_requests AS br
    ON br.booking_id = a.booking_id
WHERE br.space_code LIKE 'DG%'
GROUP BY a.decision_method
ORDER BY a.decision_method;
GO

/* Must return 0: approved-lifecycle bookings do not overlap each other. */
SELECT COUNT_BIG(*) AS approved_booking_overlap_pairs_should_be_zero
FROM dbo.booking_requests AS b1
INNER JOIN dbo.booking_requests AS b2
    ON b2.space_code = b1.space_code
   AND b2.booking_id > b1.booking_id
   AND b1.requested_start_time < b2.requested_end_time
   AND b1.requested_end_time > b2.requested_start_time
WHERE b1.space_code LIKE 'DG%'
  AND b2.space_code LIKE 'DG%'
  AND b1.booking_status IN (N'approved', N'checked in', N'completed', N'no-show')
  AND b2.booking_status IN (N'approved', N'checked in', N'completed', N'no-show');
GO

/* Normal out-of-service maintenance should not overlap generated
   approved-lifecycle bookings. The only allowed exceptions below are records
   that have advisory -> out-of-service escalation history. This query must
   return 0. */
SELECT COUNT_BIG(*) AS unintended_oos_overlap_pairs_should_be_zero
FROM dbo.maintenance_records AS mr
INNER JOIN dbo.booking_requests AS br
    ON br.space_code = mr.space_code
   AND br.requested_start_time < COALESCE(mr.completion_time, CONVERT(DATETIME2(0), '9999-12-31T23:59:59'))
   AND br.requested_end_time > mr.start_time
WHERE mr.space_code LIKE 'DG%'
  AND br.space_code LIKE 'DG%'
  AND mr.impact_level = N'out-of-service'
  AND br.booking_status IN (N'approved', N'checked in', N'completed', N'no-show')
  AND NOT EXISTS (
      SELECT 1
      FROM dbo.maintenance_impact_history AS h
      WHERE h.maintenance_id = mr.maintenance_id
        AND h.previous_impact_level = N'advisory'
        AND h.new_impact_level = N'out-of-service'
  );
GO

/* Intentional escalation overlap rows: should be > 0 so the affected-booking
   report has data to return. */
SELECT COUNT_BIG(*) AS intentional_escalation_affected_booking_pairs
FROM dbo.maintenance_records AS mr
INNER JOIN dbo.booking_requests AS br
    ON br.space_code = mr.space_code
   AND br.requested_start_time < COALESCE(mr.completion_time, CONVERT(DATETIME2(0), '9999-12-31T23:59:59'))
   AND br.requested_end_time > mr.start_time
WHERE mr.space_code LIKE 'DG%'
  AND br.space_code LIKE 'DG%'
  AND br.booking_status IN (N'approved', N'checked in', N'completed', N'no-show')
  AND EXISTS (
      SELECT 1
      FROM dbo.maintenance_impact_history AS h
      WHERE h.maintenance_id = mr.maintenance_id
        AND h.previous_impact_level = N'advisory'
        AND h.new_impact_level = N'out-of-service'
  );
GO

PRINT N'Generated Phase 2 dataset loaded successfully.';
GO
